server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848 #配置Nacos地址
        # 换成nginx的7778端口，做集群
        server-addr: 127.0.0.1:7778

management:
  endpoints:
    web:
      exposure:
        include: '*'